export { default as LoginForm } from './LoginForm.vue'
export { default as RegisterForm } from './RegisterForm.vue'
export { default as EmailVerification } from './EmailVerification.vue'
export { default as ForgotPassword } from './ForgotPassword.vue'
export { default as ResetPassword } from './ResetPassword.vue'
export { default as ProfileManager } from './ProfileManager.vue'